name: Publish Package to npmjs
on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build:
    permissions:
      packages: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          always-auth: true
          cache: "pnpm"
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile
        name: Install Dependancies

      - run: pnpm tsc --noEmit
        name: Type Check

      - run: pnpm test
        name: Test

      - run: pnpm build
        name: Build

      - name: create and publish versions
        uses: changesets/action@v1
        id: create_and_publish_versions
        with:
          publish: pnpm publish:ci
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.YARN_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}