name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          always-auth: true
          cache: "pnpm"
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile
        name: Install Dependancies

      - run: pnpm tsc --noEmit
        name: Type Check

      - run: pnpm test
        name: Test

      - run: pnpm build
        name: Build

      # Publish NPM
      # - run: pnpm publish
      #   name: Publish to NPMJS
      #   if: always()
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          publish: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.YARN_TOKEN }}