name: Run Tests
on:
  pull_request:
    branches:
      - master
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          always-auth: true
          cache: "pnpm"
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile
        name: Install Dependancies

      - run: pnpm tsc --noEmit
        name: Type Check

      - run: pnpm test
        name: Test